import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navbar/navbar";


export const metadata: Metadata = {
  title: "PPS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <div>
          <NavBar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
